# Generated by Django 5.0.4 on 2024-04-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('walk_in', 'Walk in'), ('reference', 'Reference'), ('social_media', 'Social Media'), ('google', 'Google')], max_length=20)),
                ('customer_type', models.CharField(choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=20)),
                ('birthday_date', models.DateField()),
                ('anniversary_date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=20)),
                ('lead_assigned_to', models.CharField(max_length=20)),
            ],
        ),
    ]
