# Generated by Django 5.0.4 on 2024-05-23 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('template_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('template_name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='crm.company')),
            ],
        ),
        migrations.AlterField(
            model_name='messagehistory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.templatehistory'),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
