# Generated by Django 5.0.4 on 2024-05-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_mastertemplate_templatehistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='anniversary_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='birthday_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='city',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='customer_type',
            field=models.CharField(choices=[('diamond', 'Diamond'), ('gold', 'Gold'), ('silver', 'Silver')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='lead_assigned_to',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='lead_type',
            field=models.CharField(choices=[('walk_in', 'Walk in'), ('reference', 'Reference'), ('social_media', 'Social Media'), ('google', 'Google')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='state',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
