# Generated by Django 5.0.4 on 2024-05-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customerdetail_anniversary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertemplate',
            name='header_content',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
