# Generated by Django 5.0.4 on 2024-05-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_mastertemplate_header_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('message_to', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
            ],
        ),
    ]
